version: 2

sources:
  - name: silver
    database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
    schema: SILVER
    tables:
      - name: LEAGUEPEDIA_TOURNAMENTS
      - name: LEAGUEPEDIA_PLAYERS
      - name: LEAGUEPEDIA_TOURNAMENT_ROSTERS
      - name: LEAGUEPEDIA_PLAYER_SOLOQUEUE_ACCOUNTS