dbt_gold_layer:
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_DBT_USER') }}"
      password: "{{ env_var('SNOWFLAKE_DBT_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_DBT_ROLE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      schema: GOLD
      threads: 4
  target: dev
