"""Schéma de données pour les joueurs leaguepedia."""


class PlayersSchema:
    """Schéma avec métadonnées de format pour joueurs leaguepedia."""

    PLAYERS_SCHEMA = {
        "id": {"type": "str", "missing_value": None},
        "overview_page": {"type": "str", "missing_value": None},
        "player": {"type": "str", "missing_value": None},
        "image": {"type": "str", "missing_value": None},
        "name": {"type": "str", "missing_value": None},
        "native_name": {"type": "str", "missing_value": None},
        "name_alphabet": {"type": "str", "missing_value": None},
        "name_full": {"type": "str", "missing_value": None},
        "country": {"type": "str", "missing_value": None},
        "nationality": {"type": "str", "missing_value": None},
        "nationality_primary": {"type": "str", "missing_value": None},
        "age": {"type": "int", "missing_value": 0},
        "birthdate": {"type": "date", "missing_value": None},
        "deathdate": {"type": "date", "missing_value": None},
        "residency_former": {"type": "str", "missing_value": None},
        "team": {"type": "str", "missing_value": None},
        "team2": {"type": "str", "missing_value": None},
        "current_teams": {"type": "str", "missing_value": None},
        "team_system": {"type": "str", "missing_value": None},
        "team2_system": {"type": "str", "missing_value": None},
        "residency": {"type": "str", "missing_value": None},
        "role": {"type": "str", "missing_value": None},
        "contract": {"type": "str", "missing_value": None},
        "contract_text": {"type": "str", "missing_value": None},
        "fav_champs": {"type": "str", "missing_value": None},
        "soloqueue_ids": {"type": "str", "missing_value": None},
        "askfm": {"type": "str", "missing_value": None},
        "bluesky": {"type": "str", "missing_value": None},
        "discord": {"type": "str", "missing_value": None},
        "facebook": {"type": "str", "missing_value": None},
        "instagram": {"type": "str", "missing_value": None},
        "lolpros": {"type": "str", "missing_value": None},
        "dpmlol": {"type": "str", "missing_value": None},
        "reddit": {"type": "str", "missing_value": None},
        "snapchat": {"type": "str", "missing_value": None},
        "stream": {"type": "str", "missing_value": None},
        "kick": {"type": "str", "missing_value": None},
        "twitter": {"type": "str", "missing_value": None},
        "threads": {"type": "str", "missing_value": None},
        "linkedin": {"type": "str", "missing_value": None},
        "vk": {"type": "str", "missing_value": None},
        "website": {"type": "str", "missing_value": None},
        "weibo": {"type": "str", "missing_value": None},
        "youtube": {"type": "str", "missing_value": None},
        "team_last": {"type": "str", "missing_value": None},
        "role_last": {"type": "str", "missing_value": None},
        "is_retired": {"type": "bool", "missing_value": False},
        "to_wildrift": {"type": "bool", "missing_value": False},
        "to_valorant": {"type": "bool", "missing_value": False},
        "to_tft": {"type": "bool", "missing_value": False},
        "to_legends_of_runeterra": {"type": "bool", "missing_value": False},
        "to_2xko": {"type": "bool", "missing_value": False},
        "is_personality": {"type": "bool", "missing_value": False},
        "is_substitute": {"type": "bool", "missing_value": False},
        "is_trainee": {"type": "bool", "missing_value": False},
        "is_lowercase": {"type": "bool", "missing_value": False},
        "is_auto_team": {"type": "bool", "missing_value": False},
        "is_low_content": {"type": "bool", "missing_value": False},
    }
